version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradle test
  post_build:
    commands:
      - echo Build completed on `date`
      - gradle build
  install:
    commands:
      - aws cloudformation package --template-file SamTemplate.yaml --s3-bucket codepipeline-us-east-1-987802409920
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type : zip
  files:
    - NewSamTemplate.yaml
    - '*.*.class'
    - '*.*.jar'
  base-directory : 'build/classes/java/main/com'

