version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - gradle build clean
      - gradle test
  post_build:
    commands:
      - echo Build started on `date`
      - gradle build
      - mkdir -p deploy
      - cp -r build/classes/main/* deploy/
      - cp -r build/libs deploy/
      - ls -ltr deploy
      - ls -ltr build
      - echo Build completed on `date`
      - echo Build is complete
  install:
    commands:
      - aws cloudformation package --template-file SamTemplate.yaml --s3-bucket codepipeline-us-east-1-987802409920
                                   --output-template-file NewSamTemplate.yaml
artifacts:
  type : zip
  files:
    - '**/*'
  base-directory : 'deploy'